# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: de5ddff2ca12dcfb050e6ee8d2ee037e7d90be80af77ebb20a84254a02deae5b874b26a71c0be47b5905ee6018ad4c16751dbfafaca3ff3182bbac041965286b

test:
  secret_key_base: 987681405ff649ca5c65edc7c33ba0ccb753d1ba8de4b2c4a33690b920a0df69efd80f27fab78a131e2bba939ee0d327c4e63effb7308c49be3ac8fe748c9dd6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
